#!/bin/sh
set -eu

uci -q batch <<'EOF'
set system.@system[0].hostname='Beryl7'
set system.@system[0].zonename='Asia/Shanghai'
set system.@system[0].timezone='CST-8'
commit system
EOF

if uci -q get firewall.@defaults[0] >/dev/null; then
	uci -q batch <<'EOF'
set firewall.@defaults[0].flow_offloading='1'
set firewall.@defaults[0].flow_offloading_hw='1'
commit firewall
EOF
fi

if [ -x /etc/init.d/irqbalance ]; then
	/etc/init.d/irqbalance enable
fi

exit 0
